Make it possible to install in user context (without administrator privileges)
eclipse-theia/theia-blueprint pull request #29
Opened 2021-01-28 11:04 UTC by Niklas-Dahlquist

#### What it does
Enables the user to select installation type for all users or only for current user:
* All users
* Current user 

No need to have administrator access to proceed with
installation for current user.

Contributed by STMicroelectronics

#### How to test

Run the installer in user on an account without admin privileges and check that you are able to run Theia

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2021-02-08 14:50 UTC, thegecko commented
@brianking @jfaltermeier @koegel any concern with this change (once the CI works)?

2021-02-08 17:57 UTC, brianking commented
> @brianking @jfaltermeier @koegel any concern with this change (once the CI works)?

No. Whatever the industry standard is, but having it available to as many users as possible seems like the way to go.

2021-02-08 19:13 UTC, marcdumais-work requested changes
I think there should be a mention in the commit message that this is Windows-specific. For Linux one can use the .`Appimage` without admin permission, but AFAIK it will not be possible with the Debian package or on Mac.

2021-02-08 21:47 UTC, koegel commented
LGTM, this is a really nice contribution, thank you!

2021-02-09 09:16 UTC, merged

2021-02-09 09:16 UTC, thegecko commented
I've merged this as the CI failure is intermittent for this P, but not caused by it